# Generated by Django 3.0.8 on 2020-07-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_theme', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
