# Generated by Django 3.0.8 on 2020-07-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_theme', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='db1',
        ),
    ]
