# Generated by Django 3.0.8 on 2020-07-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_theme', '0004_auto_20200716_1429'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
