# Generated by Django 2.2.13 on 2020-07-21 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_theme', '0005_auto_20200716_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Office', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('Start_date', models.DateField()),
                ('Salary', models.IntegerField(default=1)),
            ],
        ),
    ]
