# Generated by Django 2.2.13 on 2020-07-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_theme', '0006_ex_excel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ex_excel',
            options={'managed': False},
        ),
    ]
