# Generated by Django 2.2.13 on 2020-07-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_theme', '0007_auto_20200722_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ex_excel',
            options={},
        ),
    ]
